ifndef XILINX_SDACCEL
$(error Environment variable XILINX_SDACCEL is required and should point to SDAccel install area)
endif

SDA_FLOW = hw_emu
GLOBAL_DEFS= -Drank=4
HOST_SRCS = main_cl.cpp
HOST_EXE_DIR=.
HOST_DEFS=$(GLOBAL_DEFS)
HOST_EXE = main_ex
HOST_CFLAGS = -g -Wall $(HOST_DEFS) -I${XILINX_SDACCEL}/runtime/include/1_2
HOST_LFLAGS = -L${XILINX_SDACCEL}/runtime/lib/x86_64 -lxilinxopencl -llmx6.0

KERNEL_SRCS = mmult.cl
KERNEL_NAME = mmult
KERNEL_DEFS = $(GLOBAL_DEFS)
KERNEL_INCS = 
KERNEL_FLAGS = 
#set target device for XCLBIN
XDEVICE=xilinx:adm-pcie-7v3:1ddr:3.0
XDEVICE_REPO_PATH=
KEEP_TEMP=1
KERNEL_DEBUG=
XCLBIN_NAME=bin_$(KERNEL_NAME)
HOST_CFLAGS+=-DTARGET_DEVICE=\"${XDEVICE}\"
#BOARD_SETUP_FILE needs to point to setup.sh generated by xbinst command
BOARD_SETUP_FILE=setup.sh
CLCC_OPT += ${KERNEL_FLAGS} --report estimate 
ifeq (${SDA_FLOW},cpu_emu)
    CLCC_OPT += -t sw_emu
    XCLBIN = ${XCLBIN_NAME}_cpu_emu.xclbin
else ifeq (${SDA_FLOW},hw_emu)
    CLCC_OPT += -t hw_emu
    XCLBIN = ${XCLBIN_NAME}_hw_emu.xclbin
else ifeq (${SDA_FLOW},hw)
    XCLBIN = ${XCLBIN_NAME}_hw.xclbin
    CLCC_OPT += -t hw
endif

HOST_ARGS = ${XCLBIN} 

include ~/WORKSPACE/SDAccel/common.mk
run: host xbin
	XCL_EMULATION_MODE=true ${HOST_EXE_DIR}/${HOST_EXE} ${HOST_ARGS}
